### ISSUE TITLE
S3 Configuration for uploading execution reports

### ISSUE THREAD

**Issue by yusufcanb** [yusufcanb/reactive-robot#6]
In the configuration file, we might have a configuration for any generic object storage like below; 

```yaml
...
s3:
  host: [S3_HOST]
  access_key [S3_ACCESS_KEY]
  secret_key: [S3_SECRET_KEY]
  bucket_name: reactive-robot
...
```

and upload robot reports with a convention like this;

- `[bucket_name]/[binding_display_name]/[YEARMONTHDAY.BUILDNUM]/report.html'`

- `[bucket_name]/[binding_display_name]/[YEARMONTHDAY.BUILDNUM]/log.html'`

- `[bucket_name]/[binding_display_name]/[YEARMONTHDAY.BUILDNUM]/output.xml'`
