### ISSUE TITLE
Hooks configuration to trigger after robot execution

### ISSUE THREAD

**Issue by yusufcanb** [yusufcanb/reactive-robot#7]
Allowing to registering hooks would be beneficial especially when we want inform the status of the robot binding to live feeds like Slack, Teams, Discord.

```yaml
hooks:
  - name: Slack
    url: https://example.com/postreceive
    content-type: application/json
    when: fail 
```
